/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package logeoproyect;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Renzo Renato
 */
public class SystemPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VistaOlvideDatos
     */
    public SystemPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TXTnomDoc = new javax.swing.JTextField();
        TXTnumDoc = new javax.swing.JTextField();
        TXTnomMedic = new javax.swing.JTextField();
        CBXlunes = new javax.swing.JCheckBox();
        CBXmiercoles = new javax.swing.JCheckBox();
        CBXmartes = new javax.swing.JCheckBox();
        CBXviernes = new javax.swing.JCheckBox();
        CBXjueves = new javax.swing.JCheckBox();
        CBXsabado = new javax.swing.JCheckBox();
        CBXdomingo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        TArecomen = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TXTminutos = new javax.swing.JTextField();
        TXThora = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        BTNalarm = new javax.swing.JButton();
        BTNguardarMedi = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TXTnomDoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(TXTnomDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 210, -1));

        TXTnumDoc.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(TXTnumDoc, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 210, -1));

        TXTnomMedic.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(TXTnomMedic, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 210, -1));

        CBXlunes.setText("LUNES");
        getContentPane().add(CBXlunes, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 280, -1, -1));

        CBXmiercoles.setText("MIERCOLES");
        getContentPane().add(CBXmiercoles, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 280, -1, -1));

        CBXmartes.setText("MARTES");
        getContentPane().add(CBXmartes, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        CBXviernes.setText("VIERNES");
        getContentPane().add(CBXviernes, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 280, -1, -1));

        CBXjueves.setText("JUEVES");
        getContentPane().add(CBXjueves, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 280, -1, -1));

        CBXsabado.setText("SABADO");
        getContentPane().add(CBXsabado, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 280, -1, -1));

        CBXdomingo.setText("DOMINGO");
        getContentPane().add(CBXdomingo, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 280, -1, -1));

        TArecomen.setColumns(20);
        TArecomen.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        TArecomen.setRows(5);
        jScrollPane1.setViewportView(TArecomen);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 360, 330, 130));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Información del doctor a cargo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setText("Nombre del doctor:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setText("Número de celular del doctor:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setText("Información del medicamento:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setText("Nombre del medicamento:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setText("Horarios del medicamento");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setText("horas");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setText("minutos");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 380, -1, -1));

        TXTminutos.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(TXTminutos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 370, 51, 30));

        TXThora.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        getContentPane().add(TXThora, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, 51, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setText("*Formato 24 horas");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 410, -1, -1));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setText("*Primero guarde los datos y despues");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, -1, -1));

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setText("active la alarma");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, -1, -1));

        BTNalarm.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNalarm.setText("ACTIVAR ALARMA");
        BTNalarm.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNalarmMouseClicked(evt);
            }
        });
        getContentPane().add(BTNalarm, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, -1, -1));

        BTNguardarMedi.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BTNguardarMedi.setText("Guardar medicamento");
        BTNguardarMedi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BTNguardarMediMouseClicked(evt);
            }
        });
        getContentPane().add(BTNguardarMedi, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 510, -1, -1));

        jButton1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton1.setText("Cerrar sesión");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 20, 130, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNguardarMediMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNguardarMediMouseClicked
        
        try {

            BufferedWriter bw = new BufferedWriter(new FileWriter("InfoMedic.txt", true));
            //capture las variables del textfield y textArea
            int hora = Integer.parseInt(TXThora.getText());
            int minutos = Integer.parseInt(TXTminutos.getText());
            String nomDoc = TXTnomDoc.getText();
            String numDoc = TXTnumDoc.getText();
            String nomMedic = TXTnomMedic.getText();
            String recomen = TArecomen.getText();

            //Capturo check box de días
            String lunes = "";
            String martes = "";
            String miercoles = "";
            String jueves = "";
            String viernes = "";
            String sabado = "";
            String domingo = "";

            if (CBXlunes.isSelected() == true) {
                lunes = "Lunes";

            }
            if (CBXmartes.isSelected() == true) {

                martes = "Martes";
            }
            if (CBXmiercoles.isSelected() == true) {

                miercoles = "Miercoles";
            }
            if (CBXjueves.isSelected() == true) {

                jueves = "Jueves";
            }
            if (CBXviernes.isSelected() == true) {

                viernes = "Viernes";
            }
            if (CBXsabado.isSelected() == true) {

                sabado = "Sabado";
            }
            if (CBXdomingo.isSelected() == true) {

                domingo = "Domingo";
            }

            JOptionPane.showMessageDialog(null, "Datos guardados exitosamente");
            System.out.println("Guardado en base de datos correctamente");

            bw.write(hora + ", " + minutos + ", " + lunes + " " + martes + " " + miercoles + " "
                     + "" + jueves + " " + viernes + " " + sabado + " " + domingo + " , " + nomDoc + ", "
                     + "" + numDoc + ", " + nomMedic + ", " + recomen);
            bw.flush();
            bw.newLine();
            bw.close();

        } catch (IOException ex) {
            Logger.getLogger(SystemPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_BTNguardarMediMouseClicked

    private void BTNalarmMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BTNalarmMouseClicked
        int hora = Integer.parseInt(TXThora.getText());
        int minutos = Integer.parseInt(TXTminutos.getText());

        hiloHora h = new hiloHora(hora, minutos);

        //proceso oProceso = new proceso(2020, 7,31, arreglohoras[i].getHour(), 0);
        h.start();
        JOptionPane.showMessageDialog(null, "Alarma establecida");
        VistaFinal vf = new VistaFinal();
        this.setVisible(false);
        vf.setVisible(true);
    }//GEN-LAST:event_BTNalarmMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        SystemLogeo sl = new SystemLogeo();
        sl.setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNalarm;
    private javax.swing.JButton BTNguardarMedi;
    private javax.swing.JCheckBox CBXdomingo;
    private javax.swing.JCheckBox CBXjueves;
    private javax.swing.JCheckBox CBXlunes;
    private javax.swing.JCheckBox CBXmartes;
    private javax.swing.JCheckBox CBXmiercoles;
    private javax.swing.JCheckBox CBXsabado;
    private javax.swing.JCheckBox CBXviernes;
    private javax.swing.JTextArea TArecomen;
    private javax.swing.JTextField TXThora;
    private javax.swing.JTextField TXTminutos;
    private javax.swing.JTextField TXTnomDoc;
    private javax.swing.JTextField TXTnomMedic;
    private javax.swing.JTextField TXTnumDoc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
